export const constants = {
    LOGIN_C:'LOGIN',
    LABEL_TEXT_LOGIN:'We will not share you number with anyone without yous permission',
    LABEL_LOGIN:'Sign In / Sign Up',
    ENTER_EMAIL_ID:'Enter Email Id',
    ENTER_PASSWORD:'Enter Password',
    MOBILE_NUMBER:'Mobile Number',
    LOGIN_BUTTON:'L O G I N',
    NEED_AN_ACCOUNT:"Need an accout ?",
    SIGN_UP:' Sign in with',
    FORGOT_PASSWORD:'Forgot Password',
    DONE:'S U B M I T',
    SIGN_UP_C: 'SIGN UP',
    LOGIN:'Login',
    ALREADY_AN_ACCOUT:'Already an account ? ',
    FIRST_NAME:'First Name',
    LAST_NAME: "Last Name",
    CONFIRMPASSWORD:'Confirm Password',
    PLACE:'Place',
    VERIFICATION_CODE:'Verification code',
    OTP_TEXT:'Please type verification code sent',
    BOOKING_ROOM:'Available Meeting Room',
    OCCUPIED_ROOM:'Occupied Meeting Room',
    MEETING_ROOM:'Meeting Room',
    SELECT_A_LOCATION:'Select a location to book a meeting room',
    SELECT_A_MEETING_ROOM:'Select a meeting room',
    TIMING:'Timing',
    ENTER_MOBILE_NUMBER :'Enter your mobile number here',
    OR:'or'

}